schema = 3

[mod]
  [mod."github.com/Baidu-AIP/golang-sdk"]
    version = "v1.1.1"
    hash = "sha256-hKshA0K92bKuK92mmtM0osVmqLJcSbeobeWSDpQoRCo="
  [mod."github.com/FloatTech/AnimeAPI"]
    version = "v1.7.1-0.20250926171956-ba37dfebfc4a"
    hash = "sha256-wtr9hgHSPsD5NqSmI3Lo8RVWE+cNMIUGo2bcsKTN8Gg="
  [mod."github.com/FloatTech/floatbox"]
    version = "v0.0.0-20251002074805-f95cbc7edb31"
    hash = "sha256-c50unGhF0JVPHN8geZM/YYQKgGqJgCtVksh4Ij1Pg+4="
  [mod."github.com/FloatTech/gg"]
    version = "v1.1.3"
    hash = "sha256-7K/R2mKjUHVnoJ3b1wDObJ5Un2Htj59Y97G1Ja1tuPo="
  [mod."github.com/FloatTech/imgfactory"]
    version = "v0.2.2-0.20230413152719-e101cc3606ef"
    hash = "sha256-2okFyPQSYIxrc8hxICsbjEM9xq25a3I2A4wmDIYFCg8="
  [mod."github.com/FloatTech/rendercard"]
    version = "v0.2.0"
    hash = "sha256-fgntEYGh2mEl618hM13kb0GGeQEXdP+lochYX8F2OXs="
  [mod."github.com/FloatTech/sqlite"]
    version = "v1.7.2"
    hash = "sha256-R9QaP5FQwtWpHdbCoNX/rYOS/CgkIeRdFB9cwJ4n/JM="
  [mod."github.com/FloatTech/ttl"]
    version = "v0.0.0-20250224045156-012b1463287d"
    hash = "sha256-C5xBt0roPgahradCOTgkhL+j5bvoSXmGwdqcu0aSczc="
  [mod."github.com/FloatTech/zbpctrl"]
    version = "v1.7.0"
    hash = "sha256-HDDnE0oktWJH1tkxuQwUUbeJhmVwY5fyc/vR72D2mkU="
  [mod."github.com/FloatTech/zbputils"]
    version = "v1.7.2-0.20251002080916-b554b7039913"
    hash = "sha256-9z7c79uuFl2LKaCgW1gQN5lmMjgKIcKrakcBlb3zJ90="
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.8.0"
    hash = "sha256-I3QaPWATvBOL/F26fIiYWKS13yBUYo+9o3tcsGIu8tY="
  [mod."github.com/RomiChan/syncx"]
    version = "v0.0.0-20240418144900-b7402ffdebc7"
    hash = "sha256-L1j1vgiwqXpF9pjMoRRlrQUHzoULisw/01plaEAwxs4="
  [mod."github.com/RomiChan/websocket"]
    version = "v1.4.3-0.20251002072000-d3eb41798438"
    hash = "sha256-vLu9Va+9AbOIdh1LEetz5JlJK0P2IXKsYRvCdAO8tYw="
  [mod."github.com/Tnze/go-mc"]
    version = "v1.20.2"
    hash = "sha256-Nu4PXNxeARH0itm6yIIplFaywL2yQnPJFksmmuyIptI="
  [mod."github.com/adamzy/cedar-go"]
    version = "v0.0.0-20170805034717-80a9c64b256d"
    hash = "sha256-N19KTxh70IUBqnchFuWkrJD8uuFOIVqv1iSuN3YFIT0="
  [mod."github.com/ajstarks/svgo"]
    version = "v0.0.0-20200320125537-f189e35d30ca"
    hash = "sha256-ALeRuEJN9jHjGb4wNKJcxC59vVx8Tj7hHikEGkaZZ0s="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.1"
    hash = "sha256-M0u22DXSeXUaYtl1KoW1qWL46niFpycFkraCEQ/luYA="
  [mod."github.com/antchfx/htmlquery"]
    version = "v1.3.4"
    hash = "sha256-nrtIgRgdOvo0iIQyrhHOFKOmoT8e2gduUsct3f5zDNA="
  [mod."github.com/antchfx/xpath"]
    version = "v1.3.3"
    hash = "sha256-Ent9bgBTjKS8/61LKrIu/JcBI/Qsv6EEIojwsMjCgdY="
  [mod."github.com/corona10/goimagehash"]
    version = "v1.1.0"
    hash = "sha256-HyS8nc7kUNnDaVBDzJ9Ym4pRs83YB4M2vHSRwfm6mr4="
  [mod."github.com/davidscholberg/go-durationfmt"]
    version = "v0.0.0-20170122144659-64843a2083d3"
    hash = "sha256-0rdbpBf3AAjMpxvVEGFb2ImgB2i7vdEhIwCyqJs1iHE="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/ebitengine/oto/v3"]
    version = "v3.3.2"
    hash = "sha256-TPu3qvJscLZbjwIqC3jj0T1md0mX3lQxcC8GAk7kB1w="
  [mod."github.com/ebitengine/purego"]
    version = "v0.8.0"
    hash = "sha256-fM+5HYIKDPLDrvv2f9/WQG0F20+o0+At0AbPQtF2JP0="
  [mod."github.com/ericpauley/go-quantize"]
    version = "v0.0.0-20200331213906-ae555eb2afa4"
    hash = "sha256-sMN6D7IlDpDqUWM8ppoE5Sdb7DvLAJaN6qAucBWJ3rs="
  [mod."github.com/fumiama/ahsai"]
    version = "v0.1.1"
    hash = "sha256-knYw0R5fhjE/asc/TwlGJDzVr+Oaj8sH7kr7x6Mqs3E="
  [mod."github.com/fumiama/cron"]
    version = "v1.3.0"
    hash = "sha256-/sN7X8dKXQgv8J+EDzVUB+o+AY9gBC8e1C6sYhaTy1k="
  [mod."github.com/fumiama/deepinfra"]
    version = "v0.0.0-20250924162107-cf156d49a0fa"
    hash = "sha256-D0lgA7jBDLE8v9ePDiWwH439eB5+cDlj2fKRAc0wUms="
  [mod."github.com/fumiama/go-base16384"]
    version = "v1.7.0"
    hash = "sha256-vTAsBBYe2ISzb2Nba5E96unodZSkhMcqo6hbwR01nz8="
  [mod."github.com/fumiama/go-onebot-agent"]
    version = "v0.0.0-20250926145606-37ebfa6131c8"
    hash = "sha256-oq1SSyddsXhsFvSHFhqSEAF9SH03b2jI0KvGbsFPXYQ="
  [mod."github.com/fumiama/go-registry"]
    version = "v0.2.7"
    hash = "sha256-Rjl+z0Hlp2LMi8+pnFe5HrxctyHMi7UPiK33g/OgLdA="
  [mod."github.com/fumiama/go-simple-protobuf"]
    version = "v0.2.0"
    hash = "sha256-2kULBi1sXsFDX2g/KRFmCGkwF60o/UXacNUbIYa/cvw="
  [mod."github.com/fumiama/gofastTEA"]
    version = "v0.1.3"
    hash = "sha256-/Qu57mkkFt7aFufhlkMYPgrWj5XCGbuM28EHDD8w4XY="
  [mod."github.com/fumiama/gotracemoe"]
    version = "v0.0.3"
    hash = "sha256-O3cDkVXu5NG1ZtzubxhH+S91zfgu4uH1L+OiSGYSNXQ="
  [mod."github.com/fumiama/imgsz"]
    version = "v0.0.4"
    hash = "sha256-rrGx+v41OEl0ATwL6u5TNcpfkCQbj3jFNnGiQUNu2qs="
  [mod."github.com/fumiama/jieba"]
    version = "v0.0.0-20221203025406-36c17a10b565"
    hash = "sha256-DvDx1pdldkdaSszrbadM/VwqT9TTSmWl6G6a+ysXYEM="
  [mod."github.com/fumiama/orbyte"]
    version = "v0.0.0-20251002065953-3bb358367eb5"
    hash = "sha256-mRQwhR0v922UXlJ7lXo/osv21K8kZDaHx3DsBCjmzoo="
  [mod."github.com/fumiama/slowdo"]
    version = "v0.0.0-20241001074058-27c4fe5259a4"
    hash = "sha256-rsV3MKRCSOBMIgJXFCGbCHRY2aBAb32ftU49hT3GjqY="
  [mod."github.com/fumiama/terasu"]
    version = "v0.0.0-20251006080703-541b84ca4a5f"
    hash = "sha256-FQnOlahP7384Z2TFOCVWOjsWB/aqpbumPOwCo4TlI/k="
  [mod."github.com/fumiama/unibase2n"]
    version = "v0.0.0-20240530074540-ec743fd5a6d6"
    hash = "sha256-I3xNzjrj5y0fy0dfa75V57GanfmHIHmubEn9/y0BBHw="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.2.6"
    hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gopxl/beep/v2"]
    version = "v2.1.1"
    hash = "sha256-JLCUJCG+VvNlVF296JWIOUvvUFHlqEAJvZfw853qwwU="
  [mod."github.com/jfreymuth/oggvorbis"]
    version = "v1.0.5"
    hash = "sha256-jphTCaPr34ZT9Id4ZZ6zU9Vnxzy6cTjCwjpQ819eGV0="
  [mod."github.com/jfreymuth/vorbis"]
    version = "v1.0.2"
    hash = "sha256-gVS+/PZ5pDnswpTQNZILcrx5ZNq9ShXd6vXn7Jabes4="
  [mod."github.com/jinzhu/gorm"]
    version = "v1.9.16"
    hash = "sha256-qKEwgNE8NxcX1uzT20LwC1TKVmve/nIy+oxdAKlxAuc="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/jozsefsallai/gophersauce"]
    version = "v1.0.1"
    hash = "sha256-29DsfnGmK51DPunR/leRBKCcokN/yLoB7S2HxCsqtgY="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/kanrichan/resvg-go"]
    version = "v0.0.2-0.20231001163256-63db194ca9f5"
    hash = "sha256-plRZ3yhyCafCXmAD4vnFUoCTRsHmLp7Jn9gFKcEKbds="
  [mod."github.com/lithammer/fuzzysearch"]
    version = "v1.1.8"
    hash = "sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do="
  [mod."github.com/liuzl/cedar-go"]
    version = "v0.0.0-20170805034717-80a9c64b256d"
    hash = "sha256-N19KTxh70IUBqnchFuWkrJD8uuFOIVqv1iSuN3YFIT0="
  [mod."github.com/liuzl/da"]
    version = "v0.0.0-20180704015230-14771aad5b1d"
    hash = "sha256-J43kwDFmB6LzDhS3Ig/4ddZUTXz1cKztbTA3hILScs8="
  [mod."github.com/liuzl/gocc"]
    version = "v0.0.0-20231231122217-0372e1059ca5"
    hash = "sha256-Dr1xDbO+eR4Y/EpPgQ/S6g6C5etRFKWr8de77skcJR8="
  [mod."github.com/lufia/plan9stats"]
    version = "v0.0.0-20211012122336-39d0f177ccd0"
    hash = "sha256-thb+rkDx5IeWMgw5/5jgu5gZ+6RjJAUXeMgSkJHhRlA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mmcdole/gofeed"]
    version = "v1.3.0"
    hash = "sha256-GHpqGZvNg+3RSIkVKXrWg6/e8dJD8Y5v2Sx6MzmRlQ0="
  [mod."github.com/mmcdole/goxpp"]
    version = "v1.1.1-0.20240225020742-a0c311522b23"
    hash = "sha256-2pGg+LxHHQn2lwQBvc7EtrpMwZbZF7qepglzhS3TfW4="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/mroth/weightedrand"]
    version = "v1.0.0"
    hash = "sha256-bP+yIaBUY5+oI455mNM8zh14z/SNPaQg44L3RJ0/v/c="
  [mod."github.com/ncruces/go-strftime"]
    version = "v0.1.9"
    hash = "sha256-T0iw+UEckzueWHT88PkTnZZixyKCEa+DTLzIiiohuWY="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/notnil/chess"]
    version = "v1.10.0"
    hash = "sha256-hsUOS4rVuMW+UCPJzhsZh3PHCi1Lol12BwKujcICayo="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20210728143218-7b4eea64cf58"
    hash = "sha256-QI+F1oPLOOtwNp8+m45OOoSfYFs3QVjGzE0rFdpF/IA="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkumza/numcn"]
    version = "v1.0.0"
    hash = "sha256-cPxqj5tb10+MurN1Lehkk/v8KjaxXpL08+pVgL4x4Hg="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20210106213030-5aafc221ea8c"
    hash = "sha256-ywykDYuqcMt0TvZOz1l9Z6Z2JMTYQw8cP2fT8AtpmX4="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/shirou/gopsutil/v3"]
    version = "v3.24.5"
    hash = "sha256-tc+t1u7gf5A+Bd956dYeM8pGbxs9ezQHqKAKfLQLpuQ="
  [mod."github.com/shoenig/go-m1cpu"]
    version = "v0.1.6"
    hash = "sha256-hT+JP30BBllsXosK/lo89HV/uxxPLsUyO3dRaDiLnCg="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.5.0"
    hash = "sha256-fGdJM4LJrZA9jxHuYVo4EUQ3I1k0IVG3QQCBCgZkeZI="
  [mod."github.com/tidwall/gjson"]
    version = "v1.18.0"
    hash = "sha256-CO6hqDu8Y58Po6A01e5iTpwiUBQ5khUZsw7czaJHw0I="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/tklauser/go-sysconf"]
    version = "v0.3.12"
    hash = "sha256-91VBZNb3L2TZkEETF1AE4wnraLoGxKeofUbC5ZiWVHk="
  [mod."github.com/tklauser/numcpus"]
    version = "v0.6.1"
    hash = "sha256-8eFcw4YI0w6+GPhU5xMMQjiio94q/O5PpNO3QsvXve0="
  [mod."github.com/wcharczuk/go-chart/v2"]
    version = "v2.1.2"
    hash = "sha256-GXWWea/u6BezTsPPrWhTYiTetPP/YW6P+Sj4YdocPaM="
  [mod."github.com/wdvxdr1123/ZeroBot"]
    version = "v1.8.2-0.20251002074418-56567b7fc282"
    hash = "sha256-KaoqopWcXqiRhGYNaA3UqYtXf27yMuBEj/bvqOWxaC4="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."gitlab.com/gomidi/midi/v2"]
    version = "v2.3.16"
    hash = "sha256-o+6UtQH+TRSQlcX8J53esAA/b2c9e7BY7gcO5iSeOy0="
  [mod."golang.org/x/image"]
    version = "v0.31.0"
    hash = "sha256-ZFTlu9+4QToPPLA8C5UcG2eq/lQylq81RoG/WtYo9rg="
  [mod."golang.org/x/net"]
    version = "v0.43.0"
    hash = "sha256-bf3iQFrsC8BoarVaS0uSspEFAcr1zHp1uziTtBpwV34="
  [mod."golang.org/x/sys"]
    version = "v0.36.0"
    hash = "sha256-9h4SHGnlJzmTENUp6226hC8fQ73QrQC3D85NNMxLuXg="
  [mod."golang.org/x/text"]
    version = "v0.29.0"
    hash = "sha256-2cWBtJje+Yc+AnSgCANqBlIwnOMZEGkpQ2cFI45VfLI="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/libc"]
    version = "v0.0.0-20240530081950-6f6d8586b5c5"
    hash = "sha256-SJYYRaiDUmIbqy9l/IgiT/4VkFsPYsaslqGEowut34w="
    replaced = "github.com/fumiama/libc"
  [mod."modernc.org/mathutil"]
    version = "v1.6.0"
    hash = "sha256-lfuEiS1odd2TWrTylnaGihSJ9myqKs3FLdpvd7PqTnE="
  [mod."modernc.org/memory"]
    version = "v1.8.0"
    hash = "sha256-ucvPr73zg8LjvU+bcoIPKTgwgcon3U9VhKrLEMH81xg="
  [mod."modernc.org/sqlite"]
    version = "v1.29.10-simp"
    hash = "sha256-HCUVN6gZDG0g2WIsQ4ksqE1+XR1IjxvnqEBEU2MO1eE="
    replaced = "github.com/fumiama/sqlite3"
