schema = 3

[mod]
  [mod."github.com/Baidu-AIP/golang-sdk"]
    version = "v1.1.1"
    hash = "sha256-hKshA0K92bKuK92mmtM0osVmqLJcSbeobeWSDpQoRCo="
  [mod."github.com/FloatTech/AnimeAPI"]
    version = "v1.7.1-0.20250112071824-df647215d106"
    hash = "sha256-z2g+JVlY+X8zEPMNuqJx3A/+Eu1FDFtbh/3jdkPPDrs="
  [mod."github.com/FloatTech/floatbox"]
    version = "v0.0.0-20241106130736-5aea0a935024"
    hash = "sha256-hSKmkzpNZwXRo0qm4G+1lXkNzWMwV9leYlYLQuzWx3M="
  [mod."github.com/FloatTech/gg"]
    version = "v1.1.3"
    hash = "sha256-7K/R2mKjUHVnoJ3b1wDObJ5Un2Htj59Y97G1Ja1tuPo="
  [mod."github.com/FloatTech/imgfactory"]
    version = "v0.2.2-0.20230413152719-e101cc3606ef"
    hash = "sha256-2okFyPQSYIxrc8hxICsbjEM9xq25a3I2A4wmDIYFCg8="
  [mod."github.com/FloatTech/rendercard"]
    version = "v0.2.0"
    hash = "sha256-fgntEYGh2mEl618hM13kb0GGeQEXdP+lochYX8F2OXs="
  [mod."github.com/FloatTech/sqlite"]
    version = "v1.7.0"
    hash = "sha256-ucSPM49W5ykkB8rj+ApxjwJZBHABl4kkGvKCgXNavow="
  [mod."github.com/FloatTech/ttl"]
    version = "v0.0.0-20240716161252-965925764562"
    hash = "sha256-/XjfdVXEzYgeM+OYuyy76tf13lO91vCcwpjWgkRGteU="
  [mod."github.com/FloatTech/zbpctrl"]
    version = "v1.7.0"
    hash = "sha256-HDDnE0oktWJH1tkxuQwUUbeJhmVwY5fyc/vR72D2mkU="
  [mod."github.com/FloatTech/zbputils"]
    version = "v1.7.2-0.20241106140112-708bfd074ddd"
    hash = "sha256-wuoobm/N4TwLc3/u7wbj/xH+C6tIiTMvbzQxKm70EIk="
  [mod."github.com/RomiChan/syncx"]
    version = "v0.0.0-20240418144900-b7402ffdebc7"
    hash = "sha256-L1j1vgiwqXpF9pjMoRRlrQUHzoULisw/01plaEAwxs4="
  [mod."github.com/RomiChan/websocket"]
    version = "v1.4.3-0.20220227141055-9b2c6168c9c5"
    hash = "sha256-Adx+gvqB+CCoUXx7ebIaBDjVkav+wS5qZPmaqcApBWA="
  [mod."github.com/adamzy/cedar-go"]
    version = "v0.0.0-20170805034717-80a9c64b256d"
    hash = "sha256-N19KTxh70IUBqnchFuWkrJD8uuFOIVqv1iSuN3YFIT0="
  [mod."github.com/ajstarks/svgo"]
    version = "v0.0.0-20200320125537-f189e35d30ca"
    hash = "sha256-ALeRuEJN9jHjGb4wNKJcxC59vVx8Tj7hHikEGkaZZ0s="
  [mod."github.com/antchfx/htmlquery"]
    version = "v1.3.4"
    hash = "sha256-nrtIgRgdOvo0iIQyrhHOFKOmoT8e2gduUsct3f5zDNA="
  [mod."github.com/antchfx/xpath"]
    version = "v1.3.3"
    hash = "sha256-Ent9bgBTjKS8/61LKrIu/JcBI/Qsv6EEIojwsMjCgdY="
  [mod."github.com/corona10/goimagehash"]
    version = "v1.1.0"
    hash = "sha256-HyS8nc7kUNnDaVBDzJ9Ym4pRs83YB4M2vHSRwfm6mr4="
  [mod."github.com/davidscholberg/go-durationfmt"]
    version = "v0.0.0-20170122144659-64843a2083d3"
    hash = "sha256-0rdbpBf3AAjMpxvVEGFb2ImgB2i7vdEhIwCyqJs1iHE="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/ericpauley/go-quantize"]
    version = "v0.0.0-20200331213906-ae555eb2afa4"
    hash = "sha256-sMN6D7IlDpDqUWM8ppoE5Sdb7DvLAJaN6qAucBWJ3rs="
  [mod."github.com/faiface/beep"]
    version = "v1.1.0"
    hash = "sha256-66qAbnJjUjhXofxlGCa6G1+vjQcSTyN/POCZvYzHaQo="
  [mod."github.com/fumiama/ahsai"]
    version = "v0.1.0"
    hash = "sha256-lSoos+SFjALcL0ZYPsbOb8wntwn2fcubvSsz0YKgL9c="
  [mod."github.com/fumiama/cron"]
    version = "v1.3.0"
    hash = "sha256-/sN7X8dKXQgv8J+EDzVUB+o+AY9gBC8e1C6sYhaTy1k="
  [mod."github.com/fumiama/go-base16384"]
    version = "v1.7.0"
    hash = "sha256-vTAsBBYe2ISzb2Nba5E96unodZSkhMcqo6hbwR01nz8="
  [mod."github.com/fumiama/go-registry"]
    version = "v0.2.7"
    hash = "sha256-Rjl+z0Hlp2LMi8+pnFe5HrxctyHMi7UPiK33g/OgLdA="
  [mod."github.com/fumiama/go-simple-protobuf"]
    version = "v0.2.0"
    hash = "sha256-2kULBi1sXsFDX2g/KRFmCGkwF60o/UXacNUbIYa/cvw="
  [mod."github.com/fumiama/gofastTEA"]
    version = "v0.0.10"
    hash = "sha256-FOCbkXoS8s/K54yZbhX5pmaN/ouELnCHZoNS8a90VAg="
  [mod."github.com/fumiama/gotracemoe"]
    version = "v0.0.3"
    hash = "sha256-O3cDkVXu5NG1ZtzubxhH+S91zfgu4uH1L+OiSGYSNXQ="
  [mod."github.com/fumiama/imgsz"]
    version = "v0.0.4"
    hash = "sha256-rrGx+v41OEl0ATwL6u5TNcpfkCQbj3jFNnGiQUNu2qs="
  [mod."github.com/fumiama/jieba"]
    version = "v0.0.0-20221203025406-36c17a10b565"
    hash = "sha256-DvDx1pdldkdaSszrbadM/VwqT9TTSmWl6G6a+ysXYEM="
  [mod."github.com/fumiama/slowdo"]
    version = "v0.0.0-20241001074058-27c4fe5259a4"
    hash = "sha256-rsV3MKRCSOBMIgJXFCGbCHRY2aBAb32ftU49hT3GjqY="
  [mod."github.com/fumiama/terasu"]
    version = "v0.0.0-20241027183601-987ab91031ce"
    hash = "sha256-WiG5BD1Icwq61KpqkQdf6dl64jEhaDJb2zAQROqXwvc="
  [mod."github.com/fumiama/unibase2n"]
    version = "v0.0.0-20240530074540-ec743fd5a6d6"
    hash = "sha256-I3xNzjrj5y0fy0dfa75V57GanfmHIHmubEn9/y0BBHw="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.0.4"
    hash = "sha256-5hl9zBo3nkPt8dZfcLoOix8lAKLm3qIkWhopoS4V34E="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.2.6"
    hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hajimehoshi/oto"]
    version = "v0.7.1"
    hash = "sha256-eRgbEbsziY5F0oI7wAe29FepZG7uGmq2M4deouDHcXI="
  [mod."github.com/jfreymuth/oggvorbis"]
    version = "v1.0.1"
    hash = "sha256-DpkiTLxAA/iCoiylpNRvMzvaDWtK+U4UMJYNnnCmJMU="
  [mod."github.com/jfreymuth/vorbis"]
    version = "v1.0.0"
    hash = "sha256-6kTol+g3NnZ3MazD786fvraw7ydUf0RWNBzHpzgN9Jk="
  [mod."github.com/jinzhu/gorm"]
    version = "v1.9.16"
    hash = "sha256-qKEwgNE8NxcX1uzT20LwC1TKVmve/nIy+oxdAKlxAuc="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/jozsefsallai/gophersauce"]
    version = "v1.0.1"
    hash = "sha256-29DsfnGmK51DPunR/leRBKCcokN/yLoB7S2HxCsqtgY="
  [mod."github.com/kanrichan/resvg-go"]
    version = "v0.0.2-0.20231001163256-63db194ca9f5"
    hash = "sha256-plRZ3yhyCafCXmAD4vnFUoCTRsHmLp7Jn9gFKcEKbds="
  [mod."github.com/lithammer/fuzzysearch"]
    version = "v1.1.8"
    hash = "sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do="
  [mod."github.com/liuzl/cedar-go"]
    version = "v0.0.0-20170805034717-80a9c64b256d"
    hash = "sha256-N19KTxh70IUBqnchFuWkrJD8uuFOIVqv1iSuN3YFIT0="
  [mod."github.com/liuzl/da"]
    version = "v0.0.0-20180704015230-14771aad5b1d"
    hash = "sha256-J43kwDFmB6LzDhS3Ig/4ddZUTXz1cKztbTA3hILScs8="
  [mod."github.com/liuzl/gocc"]
    version = "v0.0.0-20231231122217-0372e1059ca5"
    hash = "sha256-Dr1xDbO+eR4Y/EpPgQ/S6g6C5etRFKWr8de77skcJR8="
  [mod."github.com/lufia/plan9stats"]
    version = "v0.0.0-20211012122336-39d0f177ccd0"
    hash = "sha256-thb+rkDx5IeWMgw5/5jgu5gZ+6RjJAUXeMgSkJHhRlA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mroth/weightedrand"]
    version = "v1.0.0"
    hash = "sha256-bP+yIaBUY5+oI455mNM8zh14z/SNPaQg44L3RJ0/v/c="
  [mod."github.com/ncruces/go-strftime"]
    version = "v0.1.9"
    hash = "sha256-T0iw+UEckzueWHT88PkTnZZixyKCEa+DTLzIiiohuWY="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/notnil/chess"]
    version = "v1.9.0"
    hash = "sha256-2bHp/H5hBE/hPMT1HLOBqMaCZ/DYWJMDri26O9Yzoms="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20210728143218-7b4eea64cf58"
    hash = "sha256-QI+F1oPLOOtwNp8+m45OOoSfYFs3QVjGzE0rFdpF/IA="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkumza/numcn"]
    version = "v1.0.0"
    hash = "sha256-cPxqj5tb10+MurN1Lehkk/v8KjaxXpL08+pVgL4x4Hg="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20210106213030-5aafc221ea8c"
    hash = "sha256-ywykDYuqcMt0TvZOz1l9Z6Z2JMTYQw8cP2fT8AtpmX4="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/shirou/gopsutil/v3"]
    version = "v3.24.5"
    hash = "sha256-tc+t1u7gf5A+Bd956dYeM8pGbxs9ezQHqKAKfLQLpuQ="
  [mod."github.com/shoenig/go-m1cpu"]
    version = "v0.1.6"
    hash = "sha256-hT+JP30BBllsXosK/lo89HV/uxxPLsUyO3dRaDiLnCg="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.5.0"
    hash = "sha256-fGdJM4LJrZA9jxHuYVo4EUQ3I1k0IVG3QQCBCgZkeZI="
  [mod."github.com/tidwall/gjson"]
    version = "v1.18.0"
    hash = "sha256-CO6hqDu8Y58Po6A01e5iTpwiUBQ5khUZsw7czaJHw0I="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/tklauser/go-sysconf"]
    version = "v0.3.12"
    hash = "sha256-91VBZNb3L2TZkEETF1AE4wnraLoGxKeofUbC5ZiWVHk="
  [mod."github.com/tklauser/numcpus"]
    version = "v0.6.1"
    hash = "sha256-8eFcw4YI0w6+GPhU5xMMQjiio94q/O5PpNO3QsvXve0="
  [mod."github.com/wcharczuk/go-chart/v2"]
    version = "v2.1.2"
    hash = "sha256-GXWWea/u6BezTsPPrWhTYiTetPP/YW6P+Sj4YdocPaM="
  [mod."github.com/wdvxdr1123/ZeroBot"]
    version = "v1.8.0"
    hash = "sha256-3xQ+5NqZpHJdge1vrh0/bttaZt6u2ZiGtdZA0m80NBc="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."gitlab.com/gomidi/midi/v2"]
    version = "v2.1.7"
    hash = "sha256-fbgxSMCk7PVII3sNEKuGWbN56fy3eM564Xb+lnYTxRQ="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20190306152737-a1d7652674e8"
    hash = "sha256-VJ0sxFsqnx2O/NmXamL2F5bQeUw5sizVQ7NLusceK5Q="
  [mod."golang.org/x/image"]
    version = "v0.21.0"
    hash = "sha256-4HPiAlGuC9nukbUGko1kgmXt7uJxuyNHS5EnLR4Mxo4="
  [mod."golang.org/x/mobile"]
    version = "v0.0.0-20190415191353-3e0bab5405d6"
    hash = "sha256-Ds7JS9muxzDc7WgCncAd0rMSFeBI88/I0dQsk13/56k="
  [mod."golang.org/x/net"]
    version = "v0.33.0"
    hash = "sha256-9swkU9vp6IflUUqAzK+y8PytSmrKLuryidP3RmRfe0w="
  [mod."golang.org/x/sys"]
    version = "v0.29.0"
    hash = "sha256-qfsodJQ1H1CBI8yQWOvsXJgY5qHmiuw566HrrIseYHI="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/libc"]
    version = "v0.0.0-20240530081950-6f6d8586b5c5"
    hash = "sha256-SJYYRaiDUmIbqy9l/IgiT/4VkFsPYsaslqGEowut34w="
    replaced = "github.com/fumiama/libc"
  [mod."modernc.org/mathutil"]
    version = "v1.6.0"
    hash = "sha256-lfuEiS1odd2TWrTylnaGihSJ9myqKs3FLdpvd7PqTnE="
  [mod."modernc.org/memory"]
    version = "v1.8.0"
    hash = "sha256-ucvPr73zg8LjvU+bcoIPKTgwgcon3U9VhKrLEMH81xg="
  [mod."modernc.org/sqlite"]
    version = "v1.29.10-simp"
    hash = "sha256-HCUVN6gZDG0g2WIsQ4ksqE1+XR1IjxvnqEBEU2MO1eE="
    replaced = "github.com/fumiama/sqlite3"
