name: PushLint
on: [push]
jobs:
  golangci:
    name: lint_golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.17
          args: --issues-exit-code=0
      - name: Commit back
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "ğŸ¨ æ”¹è¿›ä»£ç æ ·å¼"
          git push
